### ISSUE TITLE
Example DAG fails due to xcom error

### ISSUE THREAD

**Issue by EmielStoelinga** [wmeints/mlops-airflow-sample#2]
When running the example prepare_dataset DAG, execution fails with an `'xcom' is undefined` error on the line below causing the fix_missing_values task to fail.

https://github.com/wmeints/mlops-airflow-sample/blob/60d8e1219a6181540c9e4eb936f7d873ae622c95/src/pipelines/prepare_dataset_dag.py#L42

See error log below
```
[2022-10-17, 15:01:34 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: prepare_dataset.fix_missing_values manual__2022-10-17T14:59:39.351063+00:00 [queued]>
[2022-10-17, 15:01:34 UTC] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: prepare_dataset.fix_missing_values manual__2022-10-17T14:59:39.351063+00:00 [queued]>
[2022-10-17, 15:01:34 UTC] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-17, 15:01:34 UTC] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-10-17, 15:01:34 UTC] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-17, 15:01:34 UTC] {taskinstance.py:1383} INFO - Executing <Task(PythonVirtualenvOperator): fix_missing_values> on 2022-10-17 14:59:39.351063+00:00
[2022-10-17, 15:01:34 UTC] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_dataset', 'fix_missing_values', 'manual__2022-10-17T14:59:39.351063+00:00', '--job-id', '366', '--raw', '--subdir', 'DAGS_FOLDER/prepare_dataset_dag.py', '--cfg-path', '/tmp/tmp1bmwzjpd']
[2022-10-17, 15:01:34 UTC] {standard_task_runner.py:83} INFO - Job 366: Subtask fix_missing_values
[2022-10-17, 15:01:34 UTC] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/repo/src/pipelines/prepare_dataset_dag.py
[2022-10-17, 15:01:34 UTC] {standard_task_runner.py:54} INFO - Started process 25 to run task
[2022-10-17, 15:01:35 UTC] {task_command.py:384} INFO - Running <TaskInstance: prepare_dataset.fix_missing_values manual__2022-10-17T14:59:39.351063+00:00 [running]> on host preparedatasetfixmissingvalues-2d3bd69db67d41d3adcb447fce0162c3
[2022-10-17, 15:01:35 UTC] {abstractoperator.py:421} ERROR - Exception rendering Jinja template for task 'fix_missing_values', field 'op_kwargs'. Template: {'input_data': '{{xcom.pull(task_ids="select_features")}}'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 487, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 487, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'xcom' is undefined
[2022-10-17, 15:01:35 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1576, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2199, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1192, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 414, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 487, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 487, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'xcom' is undefined
```

**Comment by EmielStoelinga** [comment]
@wmeints Could it be that when setting up the environment, a custom xcom backend was used instead of the Airflow backend?

**Comment by EmielStoelinga** [comment]
I seem to have fixed this issue by using `ti.xcom_push` instead of `xcom.push`. This is also the method that is advised [by Airflow](https://airflow.apache.org/docs/apache-airflow/stable/concepts/xcoms.html). However, this brings up another error. See the error log below. This seems to be caused by the fact that some elements of `**kwargs` in fix_missing_values.py cannot be serialised, see https://github.com/apache/airflow/issues/20974#issuecomment-1022023067. Since we only need `**kwargs` to extract `datalake_connection` and this is hard-coded as `'wasb_datalake'` elsewhere in the example, I will use this hard-code value over here as well.

I will open a pull request regarding these issues and possible further issues that I might encounter later.

```
[2022-10-19 13:29:00,575] {debug_executor.py:87} ERROR - Failed to execute task: can't pickle module objects.
Traceback (most recent call last):
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/executors/debug_executor.py", line 79, in _run_task
    ti.run(job_id=ti.job_id, **params)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1801, in run
    session=session,
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1463, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1610, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1671, in _execute_task
    result = execute_callable(context=context)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/operators/python.py", line 424, in execute
    return super().execute(context=serializable_context)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/operators/python.py", line 460, in execute_callable
    self._write_args(input_filename)
  File "/home/emiel/anaconda3/envs/mlopsdemo/lib/python3.7/site-packages/airflow/operators/python.py", line 496, in _write_args
    self.pickling_library.dump({'args': self.op_args, 'kwargs': self.op_kwargs}, file)
TypeError: can't pickle module objects
[2022-10-19 13:29:00,588] {backfill_job.py:190} ERROR - Task instance <TaskInstance: prepare_dataset.fix_missing_values backfill__2022-09-10T00:00:00+00:00 [failed]> failed
[2022-10-19 13:29:00,591] {dagrun.py:552} ERROR - Marking run <DagRun prepare_dataset @ 2022-09-10T00:00:00+00:00: backfill__2022-09-10T00:00:00+00:00, state:running, queued_at: None. externally triggered: False> failed
```

**Comment by EmielStoelinga** [comment]
PR has been opened: https://github.com/wmeints/mlops-airflow-sample/pull/5

**Comment by wmeints** [comment]
Thanks for fixing the issues.
